/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package SolveMeFirst

import java.util.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun solveMeFirst(a: Int, b: Int): Int {
    return a + b
}

fun main(args: Array<String>) {
    val sc = Scanner(System.`in`)
    val num1 = sc.nextInt()
    val num2 = sc.nextInt()
    val sum = solveMeFirst(num1, num2)
    println(sum)
}