/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package PlusMinus

import java.io.*
import java.math.*
import java.security.*
import java.text.*
import java.util.*
import java.util.concurrent.*
import java.util.function.*
import java.util.regex.*
import java.util.stream.*
import kotlin.collections.*
import kotlin.comparisons.*
import kotlin.io.*
import kotlin.jvm.*
import kotlin.jvm.functions.*
import kotlin.jvm.internal.*
import kotlin.ranges.*
import kotlin.sequences.*
import kotlin.text.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

/*
 * Complete the 'plusMinus' function below.
 *
 * The function accepts INTEGER_ARRAY arr as parameter.
 */

fun Double.format(digits: Int) = "%.${digits}f".format(this)

fun plusMinus(arr: Array<Int>): Unit {
    var x: Array<Double> = arrayOf(0.0, 0.0, 0.0)
    val n = arr.size
    for(num in arr) {
        when(num) {
            in Int.MIN_VALUE..-1 -> x[0]++
            0 -> x[1]++
            in 1..Int.MAX_VALUE -> x[2]++
        }
    }
    println("${(x[2]/n).format(6)}\n${(x[0]/n).format(6)}\n${(x[1]/n).format(6)}")
}

fun main(args: Array<String>) {
    val n = readLine()!!.trim().toInt()

    val arr = readLine()!!.trimEnd().split(" ").map{ it.toInt() }.toTypedArray()

    plusMinus(arr)
}